### PR TITLE
Concurrent triggering algorithms

### PR DESCRIPTION
**Pull request by ArturSztuc**
Allows to run multiple concurrent trigger algorithms, e.g. horizontal muon & ADC integral at the same time. 
Triggering algorithms and configs now have to be specified as arrays in the json config, so the change is from e.g.

```
        trigger_activity_plugin: TriggerActivityMakerPrescalePlugin,
        trigger_activity_config: {
            "prescale": 10000
        },
        trigger_candidate_plugin: TriggerCandidateMakerPrescalePlugin,
        trigger_candidate_config: {
            prescale: 10000
        },
```

to 

```
        trigger_activity_plugin: [TriggerActivityMakerPrescalePlugin],
        trigger_activity_config: [
            {
                "prescale": 10000
            }
        ],
        trigger_candidate_plugin: [TriggerCandidateMakerPrescalePlugin],
        trigger_candidate_config: [
            {
                prescale: 10000
            }
         ],
```
Extra triggering algorithms can be added by simply adding them to these arrays.
Important note: There must be one TCMaker for every TAMaker, the same goes for the configs. 

Briefly tested on APA2, but more testing is needed/ongoing before merging.
Need to write documentation before merging too!

### CODE REVIEW

**Comment by ArturSztuc** [comment]
Tested and working, I'll upload test results later. 
Ready for review @MRiganSUSX !

**Comment by bieryAtFnal** [comment]
Are there instructions somewhere that describe how to create a software area to test these changes?  The following steps fail to generate a configuration:

```
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest
dbt-create -c -n NAFD23-10-14 14OctFDDevConcTAMaker
cd 14OctFDDevConcTAMaker/sourcecode
git clone https://github.com/DUNE-DAQ/daqconf -b cbatchelor/concurrent_algorithms
git clone https://github.com/DUNE-DAQ/fddaqconf -b develop
git clone https://github.com/DUNE-DAQ/trigger -b develop
cd ..
dbt-workarea-env
git clone https://github.com/DUNE-DAQ/nanorc -b develop
cd nanorc
pip install -U .
cd ..
dbt-build -j 12
dbt-workarea-env

mkdir rundir
cd rundir

cat <<EOF1 > daqconf.json
{
  "boot": {
    "use_connectivity_service": true,
    "start_connectivity_service": true,
    "connectivity_service_host": "localhost",
    "connectivity_service_port": 15432
  }, 
  "daq_common": {
    "data_rate_slowdown_factor": 1
  },
  "detector": {
    "clock_speed_hz": 62500000
  },
  "readout": {
    "use_fake_cards": true,
    "default_data_file": "asset://?checksum=dd156b4895f1b06a06b6ff38e37bd798",
    "generate_periodic_adc_pattern": true,
    "emulated_TP_rate_per_ch": 1,
    "enable_tpg": true,
    "tpg_threshold": 500,
    "tpg_algorithm": "SimpleThreshold"
  },
  "trigger": {
    "trigger_window_before_ticks": 1000,
    "trigger_window_after_ticks": 1000,
    "trigger_activity_config": {
      "prescale": 25
    },
    "mlt_merge_overlapping_tcs": false
  },
  "dataflow": {
    "apps": [ { "app_name": "dataflow0" } ],
    "enable_tpset_writing": true,
    "token_count": 20
  },
  "hsi": {
    "random_trigger_rate_hz": 1.0
  }
}
EOF1

cat <<EOF2 > dro_map.json
[
    {
        "src_id": 0,
        "geo_id": {
            "det_id": 3,
            "crate_id": 1,
            "slot_id": 0,
            "stream_id": 0
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 0,
            "rx_host": "localhost",
            "rx_mac": "00:00:00:00:00:00",
            "rx_ip": "0.0.0.0",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    },
    {
        "src_id": 1,
        "geo_id": {
            "det_id": 3,
            "crate_id": 1,
            "slot_id": 0,
            "stream_id": 1
        },
        "kind": "eth",
        "parameters": {
            "protocol": "udp",
            "mode": "fix_rate",
            "rx_iface": 0,
            "rx_host": "localhost",
            "rx_mac": "00:00:00:00:00:00",
            "rx_ip": "0.0.0.0",
            "tx_host": "localhost",
            "tx_mac": "00:00:00:00:00:00",
            "tx_ip": "0.0.0.0"
        }
    }
]
EOF2

fddaqconf_gen -c ./daqconf.json --detector-readout-map-file ./dro_map.json mdapp_wibeth_tpg
```

**Comment by ArturSztuc** [comment]
@bieryAtFnal the very top message in this conversation specifies how to change the config that includes tpg to make this work.

I also started preparing a small document ([dune_multialgo.pdf](https://github.com/DUNE-DAQ/daqconf/files/12910408/dune_multialgo.pdf)) and a presentation  ([main.pdf](https://github.com/DUNE-DAQ/daqconf/files/12910409/main.pdf)), but didn't have time to finish or present because of the NOvA collaboration meeting that finished yesterday (I'm flying back to the UK today form Chicago).

**Review by eflumerf — APPROVED** [review]
Integration tests succeeded

**Comment by jcfreeman2** [comment]
Using the `kbiery/tatc_maker_arrays` branches of daqsystemtest and dfmodules, the `cbatchelor/concurrent_algorithms` branch of daqconf, and the `v1.9.1` tag of integrationtest, the following tests worked with no warnings or errors:
* `pytest -s  sourcecode/daqsystemtest/integtest/3ru_3df_multirun_test.py`
* `pytest -s  sourcecode/daqsystemtest/integtest/tpstream_writing_test.py`
* `pytest -s sourcecode/dfmodules/integtest/disabled_output_test.py`

So, LGTM.

**Comment by MRiganSUSX** [comment]
For anyone still following, I have done a round of tests:
- basic tests on configs from the Instructions page
- simple test with TPG gen
- tests on multi maker / multi APA setups:
  - 1m1a
  - 1m2a
  - 1m3a
  - 2m1a
  - 2m2a
  - 2m3a
  - 3m1a

These all run successfully. 

I also briefly checked the trigger dot files for these. There are some points of discussion for the future (noted) but it's all good for this release.

**Comment by MRiganSUSX** [comment]
Report available here:
[trigger_multi_concurrent_algos.pdf](https://github.com/DUNE-DAQ/daqconf/files/13377378/trigger_multi_concurrent_algos.pdf)

**Pull request merged**
