### PR TITLE
Changes for 2.11.1

### PR DESCRIPTION
**Pull request by jmcarcell**
This PR includes changes in DQM for
- running DQM in different hosts than readout
- support for WIB2Frames

and additionally a commit from Phil (https://github.com/DUNE-DAQ/daqconf/pull/54/commits/e0055adcdb392521d4a6a0366ea011550009bff1)

### CODE REVIEW

**Comment by philiprodrigues** [comment]
The additional commit from me should have been merged into the patch branch by https://github.com/DUNE-DAQ/daqconf/pull/47 , but I think including it here shouldn't cause a problem (git will just ignore it in the merge?)

**Comment by jmcarcell** [comment]
This is for merging the changes from 2.11.x to **develop** for 3.0.0. Are you fine with it? Sorry I was going to message you on Slack but you beat me to it. I'll solve the conflicts myself when DQM is ready

**Comment by philiprodrigues** [comment]
Oh right, sorry I misread the PR details. Yes, merging my commit into develop is fine.

**Comment by jmcarcell** [comment]
New PR without touching the 2.11.x branch in #80

**Pull request closed without merging**
