### PR TITLE
move the core utilities back into daqconf

### PR DESCRIPTION
**Pull request by plasorak**

### CODE REVIEW

**Comment by plasorak** [comment]
fixes https://github.com/DUNE-DAQ/appfwk/issues/223

**Comment by eflumerf** [comment]
https://github.com/DUNE-DAQ/appfwk/pull/229
There may be an update needed on this branch due to recent changes in `appfwk/develop`

**Comment by plasorak** [comment]
Actually, I think this is going to cause too much havoc, so let's leave it for next time. Sorry about the noise.

**Comment by bieryAtFnal** [comment]
I've updated the Tracking Project fields to reflect a Target Release of v3.0.0

**Comment by plasorak** [comment]
Here are the tests I did (I didn't run anything, just made sure that I could generate configurations):
```
 1049  daqconf_multiru_gen test
 1050  daqconf_global_gen test_global
 1051  daqconf_global_gen --master-device-name SOMETHING test_global_master_device_name
 1052  daqconf_multiru_gen --enable-dqm test_dqm
 1053  daqconf_multiru_gen --enable-software-tpg --enable-tpset-writing test_tpg_writing
 1054  daqconf_multiru_gen --use-hsi-hardware test_hsi_hardware
 1055  daqconf_multiru_gen --use-hsi-hw test_hsi_hardware
 1056  daqconf_multiru_gen --hsi-device-name whatnot --use-hsi-hw test_hsi_hardware
 1057  daqconf_multiru_gen --control-timing-partition whatnot test_control_timing_partition
 1058  daqconf_multiru_gen --control-timing-partition test_control_timing_partition
 1059  daqconf_multiru_gen --control-timing-partition --timing-partition-master-device-name whatnot test_control_timing_partition
```

**Pull request merged**
