### PR TITLE
Migrate code from minidaqapp/nanorc for creating info files describing

### PR DESCRIPTION
**Pull request by eflumerf**
the configuration command line and git tags.

### CODE REVIEW

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Comment by plasorak** [comment]
I don't understand how this build data should be constructed, but there is a lot of information in the environment:
```
$DAQCONF_DIR        $DAQCONF_INC        $DAQCONF_SHARE      $DAQCONF_VERSION
$DAQCONF_FQ_DIR     $DAQCONF_LIB        $DAQCONFSOURCE_DIR
```

**Comment by eflumerf** [comment]
The build_info is supposed to be populated. The exact directory for daqconf_dir is open for debate, but here's what I get when I installed it in my local UPS products area:
```
{
    "build_info": {
        "build time": "Tue Mar  1 10:46:33 CST 2022",
        "git branch": "eflumerf/AddInfoFiles",
        "git commit author": "Eric Flumerfelt",
        "git commit description": "Migrate code from minidaqapp/nanorc for creating info files describing the configuration command line and git tags.",
        "git commit hash": "d47a20e7eb82e2b9af225b5e25343df3a3ceb612",
        "git commit time": "Tue Mar 1 08:35:05 2022 -0600",
        "hostname for build": "ironvirt7",
        "local repo dir": "/home/eflumerf/Desktop/dune-daq-base/dev-tpset/sourcecode/daqconf",
        "uncommitted changes": "scripts/daqconf_global_gen scripts/daqconf_multiru_gen ",
        "user for build": "eflumerf"
    },
    "command_line": "/home/eflumerf/Desktop/dune-daq-base/products-local/products/daqconf/d47a20e/slf7.x86_64.e19.prof/daqconf/bin/daqconf_global_gen daqconf_multiru --disable-trace --host-thi localhost",
    "daqconf_dir": "/home/eflumerf/Desktop/dune-daq-base/products-local/products/daqconf/d47a20e/slf7.x86_64.e19.prof/daqconf"
}
```

**Comment by eflumerf** [comment]
@plasorak I wanted to avoid depending on the environment variables because they are different when you are running as a UPS product versus when you have the package checked out in `sourcecode` and are running from the local `install` directory.

**Comment by bieryAtFnal** [comment]
It's good that the build information is now populated.

For the daqconf_dir entry, I can imagine this entry meaning "the directory in which the daqconf script was found".  I can also imagine it meaning "the value of the DAQCONF_DIR env var".  But, it seems to be neither of those.  If we don't know its exact meaning, we could say that it is "a general indication of the daqconf area that was used".  That seems a little vague, but if it's the best that we can do....

**Comment by eflumerf** [comment]
OK. I have changed the name to "daqconf_exe_dir" and set it to the directory where the script was actually executing from. I added a comment to the line where the build_info.json is being found to explain the relationship between that directory and the bin directory.

**Comment by plasorak** [comment]
Ok, I supposed I'd prefer if `$DBT_INSTALL_DIR/daqconf/daqconf_build_info.json` was checked for existence and we revert to `$DAQCONF_FQ_DIR/daqconf/daqconf_build_info.json` in case it's not there (I think it would make this script a bit more readable), but your solution should work too.

**Pull request merged**
