### PR TITLE
gcrone/start connectivity service

### PR DESCRIPTION
**Pull request by gcrone**

### CODE REVIEW

**Comment by plasorak** [comment]
Just a question, there's no way this connectivity service would look like a "normal app" in the configuration, that gets fed blank json?

**Comment by gcrone** [comment]
The connectivity server won't send the completed messages at the end of a command so sending it a blank json would get an ack but then nanorc would timeout waiting for the response.

**Comment by plasorak** [comment]
gotcha, thanks

**Review by plasorak — APPROVED** [review]
Same comment as https://github.com/DUNE-DAQ/nanorc/pull/175

**Pull request merged**
