### PR TITLE
Asset manager in the configuration generation

### PR DESCRIPTION
**Pull request by plasorak**
In the hope of superseding: https://github.com/DUNE-DAQ/integrationtest/issues/29 and cleaning a bit the handling of `frames.bin`

### CODE REVIEW

**Comment by plasorak** [comment]
Still need to propagate this to `integrationtests`

**Comment by eflumerf** [comment]
One remaining question is whether it would be good to put in the idea of per-detector asset files so that we could do multiple-detector emulated readout sessions?

**Comment by plasorak** [comment]
Ah that I think I'd need some help, because it's going to be some complex combination of hardware map and frames.bin path, right?

**Review by eflumerf — APPROVED** [review]
LGTM, though we will have to add documentation about the supported paths for the `asset://` scheme

**Comment by eflumerf** [comment]
JSON file used for testing. Each of the "Broken" entries will cause a crash, so remove them to check that things are broken appropriately.

```JSON
{
"readout": {
 "enable_firmware_tpg": true,
 "use_felix": true,
  "data_files": [
    {      "detector_id": 2,      "data_file": "asset://label/ProtoWIB"    },
    {      "detector_id": 3,      "data_file": "asset://checksum/9f14e12a0ebdaf207e9e740044b2433c"    },
    {      "detector_id": 4,      "data_file": "./frames.bin"    },
    {      "detector_id": 5,      "data_file": "file:///home/eflumerf/Desktop/dune-daq-base/dev-integtest/wib2-frames.bin"    },
    {      "detector_id": 12,      "data_file": "file://wib2-frames.bin"    },
    {      "detector_id": 6,      "data_file": "asset://label/Broken"    },
    {      "detector_id": 7,      "data_file": "asset://checksum/Broken"    },
    {      "detector_id": 8,      "data_file": "asset://Broken/Broken"    },
    {      "detector_id": 9,      "data_file": "./broken.bin"    },
    {      "detector_id": 10,      "data_file": "file:///home/eflumerf/Broken.bin"    },
    {      "detector_id": 11,      "data_file": ""    }
  ]
}
}
```

**Comment by plasorak** [comment]
Actually, I now see that there are different assets (readout, trigger), so we should change a bit the query mechanism.

**Comment by plasorak** [comment]
A new way of testing:
```json
{
    "readout": {
        "data_files": [
            { "detector_id": 2,  "data_file": "asset://?label=ProtoWIB&subsystem=readout" },
            { "detector_id": 3,  "data_file": "asset://?checksum=9f14e12a0ebdaf207e9e740044b2433c" },
            { "detector_id": 4,  "data_file": "./frames.bin" },
            { "detector_id": 5,  "data_file": "/nfs/home/plasorak/swdir/runarea/frames.bin" },
            { "detector_id": 6,  "data_file": "file:///nfs/home/plasorak/swdir/runarea/frames.bin" },
            { "detector_id": 7,  "data_file": "asset://?checksum=Broken" },
            { "detector_id": 8,  "data_file": "asset://?label=Broken" },
            { "detector_id": 9,  "data_file": "asset://?Broken=Broken" },
            { "detector_id": 10, "data_file": "./broken.bin" },
            { "detector_id": 11, "data_file": "file:///home/eflumerf/Broken.bin" },
            { "detector_id": 12, "data_file": "" },
            { "detector_id": 13, "data_file": "file://wib2-frames.bin" }
            { "detector_id": 14, "data_file": "asset://?label=DuneWIB&subsystem=trigger" }
            { "detector_id": 15, "data_file": "asset://?checksum=0c9ed91bbda14d9baa170e4138d56fcd" }
        ]
    }
}
```
number 14 doesn't exist and number 15 exists, but its status isn't "valid"

**Pull request merged**
