### PR TITLE
move boot away from scripts

### PR DESCRIPTION
**Pull request by plasorak**
The changes in this PR generate bootable apps, but I haven't tried with K8s yet.

### CODE REVIEW

**Comment by eflumerf** [comment]
Does this still work without specifying a config file? e.g. `daqconf_multiru_gen default`

**Comment by plasorak** [comment]
Probably not, let me have a look

**Comment by plasorak** [comment]
Ok, this is ready now, I'll move on to `listrev` et al.

**Review by eflumerf — APPROVED** [review]
Probably my only remaining concern is the change from "daqconf" to "boot", as that will invalidate existing configurations, but I think this looks good otherwise.

**Comment by plasorak** [comment]
Ah good point. This indeed is going to make old json not working. I'll revert this back as I don't think it's a good idea to break everything now. We can keep that for next release (I think ultimately we should have a "common" and a "boot" section).

**Pull request merged**
