### PR TITLE
Robust way of getting the path to daq_app_rte.sh in forzen/nightly/ca…

### PR DESCRIPTION
**Pull request by dingp**
…ndidate releases.

### CODE REVIEW

**Comment by dingp** [comment]
In order to test the change, I put the change manually into gcc-12 release candidate on cvmfs. 

Here are the instructions to use it:

```
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest-gcc12
dbt-setup-release -b candidate rc-v3.2.0-1
```

**Comment by plasorak** [comment]
Just to make sure I understand, this code is in the first release candidate of v3.2.0? I think you're much more qualified than me to know all the env variable, so I'll accept the PR. Thanks for doing this!

**Review by plasorak — APPROVED** [review]
LGTM

**Review by eflumerf — APPROVED** [review]
LGTM too

**Comment by dingp** [comment]
> Just to make sure I understand, this code is in the first release candidate of v3.2.0? I think you're much more qualified than me to know all the env variable, so I'll accept the PR. Thanks for doing this!

Yes, it is in the first release candidate. Only reason being that it must be in the base release for a real testing.

**Pull request merged**
