### PR TITLE
Use changes on detchannelmaps branch of same name to pass serialized …

### PR DESCRIPTION
**Pull request by eflumerf**
…HWMap to Dataflow and TPWriter

Follows https://github.com/DUNE-DAQ/detchannelmaps/pull/25

### CODE REVIEW

**Comment by plasorak** [comment]
This is what the configuration looks like:

```
                    "free_space_safety_factor_for_write": 5.0,
                    "hardware_map": "J{\"link_infos\":[{\"det_crate\":1,\"det_id\":3,\"det_link\":0,\"det_slot\":0,\"dro_card\":0,\"dro_host\":\"localhost\",\"dro_link\":0,\"dro_slr\":0,\"dro_source_id\":100,\"geo_id\":65539,\"is_valid\":true},{\"det_crate\":1,\"det_id\":3,\"det_link\":1,\"det_slot\":0,\"dro_card\":0,\"dro_host\":\"localhost\",\"dro_link\":1,\"dro_slr\":0,\"dro_source_id\":101,\"geo_id\":281474976776195,\"is_valid\":true}]}",
                    "max_file_size_bytes": 4294967296,
                    "mode": "all-per-file",
                    "name": "data_store",
                    "operational_environment": "swtest",
                    "type": "HDF5DataStore"
```

I'd advocate for defining a schema and instantiating it in `daqconf` (so not changing the format of the HWMap file before daqconf).

**Comment by plasorak** [comment]
I think the changes to daqconf look good. I managed to run the `minimal_system_quick_test.py` integration test. However, with `3ru_1df_multirun_test.py`, I get a lot of:
```
 WIB fragment /TriggerRecord00009.0000/RawData/Detector_Readout_0x00000002_ProtoWIB in event TriggerRecord00009.0000 has size 37656, outside range [37192, 37192]
```

**Comment by bieryAtFnal** [comment]
Hi, sorry, some of the expected fragment sizes need to be fixed in the 3ru_1df test.  My sense is that the 3ru_3df test is working better at this point, if you want to try that one.  I will work on the 3ru_1df one soon.

**Comment by plasorak** [comment]
Cool, thanks Kurt, with 3ru 3df, it works better. I get what I think is an unrelated error:

```
2023-Mar-06 19:21:36,326 WARNING [bool dunedaq::trigger::TriggerZipper<TSET>::proc_one() [with TSET = dunedaq::trigger::Set<dunedaq::detdataformats::trigger::TriggerPrimitive>] at /tmp/root/spack-stage/spack-stage-trigger-N23-03-06-lhpecd3svbwzf56v2dnplzdi4ghvfmaf/spack-src/plugins/TriggerZipper.hpp:238] Tardy input
set from element 11. Set start time 79554162068820000 but last sent time 79554162068880000 DAQModule: zip_0
```

So from my side, this PR would be good to go.

**Review by bieryAtFnal — APPROVED** [review]
LGTM

**Pull request merged**
