### PR TITLE
Add correlation  between trigger-record-building timeout and data-request timeouts

### PR DESCRIPTION
**Pull request by bieryAtFnal**
I'm going to start this PR in a *draft* state until I have a chance to talk with people about it.

These changes are part of rationalizing several of the timeouts in the dataflow pipeline.  The end goal is to have the trigger-record-building timeout depend on the data-request timeout, and to have the DFO drain timeout at the "drain-dataflow" (previously Stop) transition depend on the trigger-record-building timeout.  This PR handles the first dependence.

As we can see from the code change, the algorithm that is currently implemented is the following:

- trb_timeout = max(MIN_TRB_TIMEOUT, SAFETY_FACTOR * max(readout/trigger_data_request_timeout)) * SYSTEM_SIZE_FACTOR + number_of_tr_sequences * SAFETY_FACTOR * 15

where

- the MIN_TRB_TIMEOUT is set to 200 msec
- the SAFETY_FACTOR applied to the data-request-timeouts is 2
- the SYSTEM_SIZE_FACTOR is the square root of the number of readout and trigger producers (I'm guessing that something less than a linear dependence will be fine)

Based on the tests that I have done, this gives us at least a safety factor of two in the trigger-record-building timeout, and we can discuss if we want to increase that.  I'll describe the tests in a follow-up post.

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
To test these changes, I made temporary code changes in several repositories.  The goal of these temporary changes was to force the Readout and Trigger fragment producers to take the maximum time that was configured, and to confirm that the TriggerRecordBuilders still had sufficient time to successfully build events even though I artificially reduced that time by a factor of two.

Here are the temporary mods:

```
diff --git a/python/daqconf/apps/readout_gen.py b/python/daqconf/apps/readout_gen.py
index b9c5870..f1a1146 100644
--- a/python/daqconf/apps/readout_gen.py
+++ b/python/daqconf/apps/readout_gen.py
@@ -110,6 +110,7 @@ def get_readout_app(RU_CONFIG=[],
                                                                                               # output_file = f"output_{idx + MIN_LINK}.out",
                                                                                               stream_buffer_size = 100 if FRONTEND_TYPE=='pac
                                                                                               request_timeout_ms = DATA_REQUEST_TIMEOUT,
+                                                                                              warn_on_timeout = False,
                                                                                               enable_raw_recording = False)))]
     if FIRMWARE_TPG_ENABLED:
         if RU_CONFIG[RUIDX]["channel_count"] > 5:
@@ -156,6 +157,7 @@ def get_readout_app(RU_CONFIG=[],
                                           output_file = path.join(RAW_RECORDING_OUTPUT_DIR, f"output_tp_{RUIDX}_{idx}.out"),
                                           stream_buffer_size = 8388608,
                                           request_timeout_ms = DATA_REQUEST_TIMEOUT,
+                                          warn_on_timeout = False,
                                           enable_raw_recording = RAW_RECORDING_ENABLED,
                                       )))]
 
@@ -232,6 +234,7 @@ def get_readout_app(RU_CONFIG=[],
                                           output_file = path.join(RAW_RECORDING_OUTPUT_DIR, f"output_{RUIDX}_{link_num}.out"),
                                           stream_buffer_size = 8388608,
                                           request_timeout_ms = DATA_REQUEST_TIMEOUT,
+                                          warn_on_timeout = False,
                                           enable_raw_recording = RAW_RECORDING_ENABLED,
                                       )))]
 
diff --git a/python/daqconf/apps/trigger_gen.py b/python/daqconf/apps/trigger_gen.py
index 3dc255a..862b891 100644
--- a/python/daqconf/apps/trigger_gen.py
+++ b/python/daqconf/apps/trigger_gen.py
@@ -244,6 +244,7 @@ def get_trigger_app(SOFTWARE_TPG_ENABLED: bool = False,
                                                                                                                  # output_file = f"output_{id
                                                                                                                  stream_buffer_size = 8388608
                                                                                                                  request_timeout_ms = DATA_RE
+                                                                                                                 warn_on_timeout = False,
                                                                                                                  enable_raw_recording = False
 
             for idy in range(tp_links):
@@ -261,6 +262,7 @@ def get_trigger_app(SOFTWARE_TPG_ENABLED: bool = False,
                                                                                                                   # output_file = f"output_{i
                                                                                                                   stream_buffer_size = 838860
                                                                                                                   request_timeout_ms = DATA_R
+                                                                                                                  warn_on_timeout = False,
                                                                                                                   enable_raw_recording = Fals
         assert(region_ids == region_ids1)
         
diff --git a/scripts/daqconf_multiru_gen b/scripts/daqconf_multiru_gen
index d7c652b..fee3d22 100755
--- a/scripts/daqconf_multiru_gen
+++ b/scripts/daqconf_multiru_gen
@@ -294,7 +294,7 @@ def cli(timing_partition_name, host_timing, port_timing, base_command_port, numb
         if enable_software_tpg or enable_firmware_tpg:
             effective_number_of_data_producers *= 2  # add in TPSet producers from Trigger (one per Link)
             effective_number_of_data_producers += len(region_id)  # add in TA producers from Trigger (one per RU)
-        trigger_record_building_timeout = int(math.sqrt(effective_number_of_data_producers) * trigger_record_building_timeout)
+        trigger_record_building_timeout = int(math.sqrt(effective_number_of_data_producers) * trigger_record_building_timeout / 2)
 
     if use_hsi_hw:
         the_system.apps["hsi"] = get_hsi_app(
```

```
diff --git a/include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx b/include/readoutlibs/models/detail/DefaultRequestHandlerMod
index 4d8eaf9..eb8d095 100644
--- a/include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx
+++ b/include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx
@@ -362,7 +362,7 @@ DefaultRequestHandlerModel<RDT, LBT>::check_waiting_requests()
       size_t size = m_waiting_requests.size();
 
       for (size_t i = 0; i < size;) {
-        if (m_waiting_requests[i].request.request_information.window_end < newest_ts) {
+        if ((m_waiting_requests[i].request.request_information.window_end+500000000) < newest_ts) {
           issue_request(m_waiting_requests[i].request, false);
           std::swap(m_waiting_requests[i], m_waiting_requests.back());
           m_waiting_requests.pop_back();
@@ -476,14 +476,14 @@ DefaultRequestHandlerModel<RDT, LBT>::data_request(dfmessages::DataRequest dr,
       << " Latency buffer occupancy=" << m_latency_buffer->occupancy();
 
     // List of safe-extraction conditions
-    if (last_ts <= start_win_ts && end_win_ts <= newest_ts) { // data is there
+    if (last_ts <= start_win_ts && (end_win_ts+500000000) <= newest_ts) { // data is there
       frag_pieces = get_fragment_pieces(start_win_ts, end_win_ts, rres);
     } else if (last_ts > start_win_ts) { // data is gone.
       frag_header.error_bits |= (0x1 << static_cast<size_t>(daqdataformats::FragmentErrorBits::kDataNotFound));
       rres.result_code = ResultCode::kNotFound;
       ++m_num_requests_old_window;
       ++m_num_requests_bad;
-    } else if (newest_ts < end_win_ts) {
+    } else if (newest_ts < (end_win_ts+500000000)) {
       if (send_partial_fragment_if_not_yet) {
         // We've been asked to send the partial fragment if we don't
         // have an object past the end of the window, so fill the
```

```
diff --git a/plugins/TCBuffer.cpp b/plugins/TCBuffer.cpp
index 9613c60..d8eac58 100644
--- a/plugins/TCBuffer.cpp
+++ b/plugins/TCBuffer.cpp
@@ -115,7 +115,7 @@ TCBuffer::do_work(std::atomic<bool>& running_flag)
                     << ", dest: " << data_request->data_destination;
       popped_anything = true;
       ++n_requests_received;
-      m_request_handler_impl->issue_request(*data_request, true);
+      m_request_handler_impl->issue_request(*data_request, false);
     }
 
     if (!popped_anything) {
```

In the tests, I modified dfmodules/integtest/minimal_system_quick_test.py and 3ru_3df_multirun_test.py to use --data-request-timeout-ms values of 50, 100, 500, and 1000 and confirmed that those two integtests worked fine in all cases.  I did these tests on the iceberg01 computer at Fermilab.

**Comment by bieryAtFnal** [comment]
The long-window-readout test indicated that we need a component of the trigger-record-building timeout that depends on the number of TR sequences in a trigger, and that is now included.

**Comment by bieryAtFnal** [comment]
I added the setting of the DFO stop timeout using a preliminary calculation of its value.

**Comment by mroda88** [comment]
Great, So tomorrow morning I'll try to run this on a large scale test and I'll try to produce some plots. I'll put the results on here so we'll see if they work.

**Review by mroda88 — APPROVED** [review]
I tested the system using
```
daqconf_multiru_gen  -n 8 -s 10 -b 20000 -a 30000 -o /data3/test --disable-trace \
                     --host-df np04-srv-002 \
                     --host-df np04-srv-002 \
                     --host-df np04-srv-003 \
                     --host-df np04-srv-004 \
                     --host-dfo np04-srv-003 \
                     --host-trigger np04-srv-019 \
                     --host-hsi np04-srv-012 \
                     --host-ru np04-srv-011 --region-id 0 \
                     --host-ru np04-srv-012 --region-id 1 \
                     --host-ru np04-srv-013 --region-id 2 \
                     --host-ru np04-srv-014 --region-id 3 \
                     --host-ru np04-srv-015 --region-id 4 \
                     --host-ru np04-srv-016 --region-id 5 \
                     --host-ru np04-srv-019 --region-id 6 \
                     --host-ru np04-srv-016 --region-id 7 \
                     --host-ru np04-srv-019 --region-id 8 \
                     --host-ru np04-srv-023 --region-id 9 \
                     --opmon-impl cern --ers-impl cern \
                     --enable-software-tpg  \
```
The test is stressful and we know some fragments were missing from the testing we did in 3.0. Yet, the TRB timeout now prevents the system to go stale and at stop the DFO does not complain that TR haven't been completed.

**Pull request merged**
