### PR TITLE
Updates from VD coldbox

### PR DESCRIPTION
**Pull request by jimbrooke**

### CODE REVIEW

**Review by philiprodrigues — COMMENTED** [review]
The changes to `trigger_gen.py` here are fine. I'm not sure how they never made it in before, actually

**Comment by eflumerf** [comment]
@jimbrooke Do you have any tips for how to test these changes? Since it's FW-TP, I'm guessing that this will have to be tested on a FELIX host, right?

**Comment by jimbrooke** [comment]
@roland-sipos the changes here to readout_gen.py are in principle the same as those in PR #162.  if in doubt @ShyamB97 will be back tomorrow or the day after.

**Comment by ShyamB97** [comment]
Hi @eflumerf, @jimbrooke is correct, the readout_gen.py changes are in https://github.com/DUNE-DAQ/daqconf/pull/162 and as testing goes, we have tested these changes with the HD coldbox last week and I didn't encounter any issues.

**Comment by eflumerf** [comment]
Should this PR then be closed in favor of #162?

**Comment by jimbrooke** [comment]
@eflumerf I think this is a question for @CharlieBatchelor @philiprodrigues . this PR resulted from a bundle of changes needed to get the VD coldbox running.  the changes for FW TPs are replicated in #162, but there were also changes for trigger.

**Comment by jimbrooke** [comment]
Also @eflumerf i just saw you question on testing. @ShyamB97 and @CharlieBatchelor should be able to point to requirements and instructions if required.  it will need a setup including a FELIX yes.

**Comment by eflumerf** [comment]
Oops, I didn't look at the header...maybe #162 should be closed in favor of this PR ;)

**Comment by eflumerf** [comment]
Replaced by #165.

**Pull request closed without merging**
