### PR TITLE
Configuration inspector

### PR DESCRIPTION
**Pull request by alessandrothea**
`daqconf_inspector` is an utility script to develop ways to meaningfully inspect and visualise DAQ configuration databases and to prototype validation algorithms. 
The set of commands is limited at the moment, but it is expected to grow.

```
Usage: daqconf_inspector [OPTIONS] CONFIG_FILE COMMAND [ARGS]...

  An utility script to develop ways to meaningfully inspect and  visualise DAQ
  configuration databases and to prototype validation algorithms.

Options:
  -i, --interactive  Start an interactive IPython session after executing the
                     commands
  -h, --help         Show this message and exit.

Commands:
  list-classes           List known classes and objects for each class
  show-object-tree       Show relationship tree
  show-objects-of-class  Show properties of objects belonging to a class
  show-sessions          Show sessions information
  validate-detstreams    Validate detector streams in the database
  validate-smart-apps    Validate smart applications in database
```

### CODE REVIEW

**Comment by eflumerf** [comment]
```
Traceback (most recent call last):
  File "/home/eflumerf/Desktop/dune-daq-base/dev-integtest-241001/install/daqconf/bin/daqconf_inspector.py", line 12, in <module>
    import IPython
ModuleNotFoundError: No module named 'IPython'
```

**Comment by alessandrothea** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/eflumerf/Desktop/dune-daq-base/dev-integtest-241001/install/daqconf/bin/daqconf_inspector.py", line 12, in <module>
>     import IPython
> ModuleNotFoundError: No module named 'IPython'
> ```

Fixed

**Review by eflumerf — APPROVED** [review]
Do we want to keep the .py extension? All of the "scripts" do not use it...

**Review by bieryAtFnal — APPROVED** [review]
Looks good.

I was able to figure out how to use all of the commands except `show-object-tree`.  When I tried to use that with "DFApplication", I got a complaint that the class was unknown, even though "DFApplication" seemed to be in the list of available classes that gets printed out.

- For that command, could a little more information be provided in the --help output?
- More generally, could the meanings of the green, blue, and red icons be added to the --help output?

A couple of typos:

- fClass {klass} unknow to configuration  # no "n" at the end of known
- Show properties of objects forma class  # forma --> from?

**Comment by alessandrothea** [comment]
> an utility script to develop ways to meaningfully inspect and visualise DAQ configuration databases and to prototype validation algorithms.

Will remove.

**Comment by alessandrothea** [comment]
@bieryAtFnal Updated `show-sessions` help

```
Usage: daqconf_inspector.py CONFIG_FILE show-sessions [OPTIONS]

  Show details of each session available in the configuration database

  For each session found in the the database, `show-session` displays:

  - The high-level session view, including segments, controllers and applications as
    hierarchical tree.
    ID and Class are shown for applications and controllers, along with their host and services (open ports)
    The icon in front of segments and appliations indicate the enable/disable.

    Optionally, it displays the path of the the database file where the object
    is define

    Legend
    ------
      ✅ : Resource enabled
      ❌ : Resource directly disabled (listed in the Session disable list)
      ⭕️ : Resource indirectly disabled by algorithm

  - The summary of session objects, including the count of referenced objects,
  the list of directly   disabled objects and the list of all disabled objects
  (directly or indirectly)

  - The session environment table.

Options:
  -p, --show-file_paths
  -h, --help             Show this message and exit.
```

**Comment by alessandrothea** [comment]
@bieryAtFnal 

Updated `show-object-tree` help

```
Usage: daqconf_inspector CONFIG_FILE show-object-tree [OPTIONS] UID

  Show the relationship tree of the OKS object with identifier UID.

  UID is the unique object identifier in the database, composed by object name
  and class name.  The UID format argument is <object name>@<class>.

  Starting from the selected object, attributes and objects refererd by
  relationships are shown recursively as hierarchical tree. By default the
  command recursively crawls through relationship without limits. The
  recursion level can be limited with the corresponding optional parameter
  (see below). In case focussing on a relationship branch is helpful, the
  focus path option (see below for details) allows to specify the branch to
  focus on, starting trom the top object. The focus path syntax combines
  relationhsip and object names, using `.` separators, and `[]` to select a
  single item in multi-value relatiosnips. The structure of the focus path
  specifier is `<relationship>[<optional object
  name>].<relationship>[<optional object name>]`. Note: specifiying the object
  name is required

  `show-object-tree` subcommand example:
      Focus on the uses.dfhw-01 relationship of df-03@DFApplication and limit the output to 5 levels below df-03
      `show-object-tree df-03@DFApplication  -f network_rules[td-trb-net-rule].descriptor -l 5`

Options:
  +a, --show-attributes / -a, --hide-attributes
                                  Show/Hide attributes
  -l, --level INTEGER             Recursion level in the object tree
  -f, --focus TEXT                Path within the object relationships to
                                  visualise
  -h, --help                      Show this message and exit.
```

**Comment by alessandrothea** [comment]
Merging this PR, more features in future ones

**Pull request merged**
