### PR TITLE
update daqconf_timing_gen to work without partition name at conf gen

### PR DESCRIPTION
**Pull request by strilov**

### CODE REVIEW

**Comment by plasorak** [comment]
Thanks for doing this Stoyan, can I ask if you have tried to run this? Otherwise all looks good

**Comment by strilov** [comment]
Hi. I've tested, and seems ok to me. Example conf gen commands (for np04) are pasted below.

`daqconf_timing_gen --host-thi np04-srv-013.cern.ch --host-tmc np04-srv-013.cern.ch --master-device-name PROD_FANOUT_1_CH --master-send-delays-period 0 timing_conf`

`daqconf_multiru_gen -d ./frames.bin -o . -s 10 --host-timing np04-srv-013.cern.ch --control-timing-partition --host-tprtc localhost --timing-partition-master-device-name PROD_FANOUT_1_CH part_conf`

**Review by plasorak — COMMENTED** [review]
LGTM

**Review by plasorak — APPROVED** [review]
Approve - not comment - so that this can be merged!

**Pull request merged**
